### ISSUE TITLE
Design improvements from Thursday May 30, 2024 meeting

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#145]
In the Thursday May 30, 2024 meeting, we agreed on many design changes. Here are my notes, but I believe @DianaTavares has mock-ups that will be even more explanatory. I do not have confidence that my notes are complete or correct, but I will share them here as a starting point, and @DianaTavares can elaborate/correct/specify.

### Buoyancy basics: Compare screen

- [x] brick on left #146 

- [x] wood on right. They do not re-brick and re-wood when changin the density back to that level. #146 

- [x] Match the font size and vertical spacing, this will compress the Blocks panel in the top right. See if it is related to maxWidth. #147 

- [x] Just make it 4kg then it will be smaller. #146 

- [x] Make similar spacing throughout the sim.  #147

- [x] Slider scale will be able to come out of the water, and will no longer be volumeless. So you can see that it is the same as the left scale which is fully out of the water. Make sure there is enough space for a 10L block. Make sure this does not disrupt Lab => fluid displaced. Or on Lab, if you want you can let it just go to the top of the water line. OK to have the scale do the same thing no matter what screen you are on.
Sliders will be taller so you can lift scale fully out of the water. #148

### Buoyancy basics: explore
- [x] combo box #151
- [x] new panel that lets you choose density #150

- [x] Custom at the top of the combo box #151

### Buoyancy:
- [x] Putting a slider on the underwater scale #148

- [x] Density accordion box will be named Density Comparison and will list all objects and the fluid. -DL: we agreed to changed to Objects Density, and not include the fluid in the Buoyancy, only in B:B. 

- [x] Reduce the size of the arrow icons in the forces panel. #149

- [x] Rename Vector Scale to Vector Zoom. #149

### Buoyancy: Lab

- [x] Open fluid displaced by default #152
- [x] Forces and Values checkboxes active by default, but leave mass values and depth lines off by default. #152

- [x] A lot of whitespace near the top of accordion boxes submerged and density. #151

**Comment by DianaTavares** [comment]
All these issues were created! and others that I include in my notes! Thanks Sam!
